version: '3.8'

services :
  api:
    container_name: api-agroleague
    image: api-agroleague
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "agroleague"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres-data-inside:/var/lib/postgresql/data"

volumes:
  postgres-data-inside: ~